sonar.projectKey=usdot-fhwa-stol_snmp-client
sonar.organization=usdot-fhwa-stol
sonar.cfamily.compile-commands=build/compile_commands.json
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=test
sonar.coverageReportPaths=build/coverage_sonar.xml