name: CI

on:
  pull_request:
  push:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.APT_REPO_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.APT_REPO_AWS_SECRET_ACCESS_KEY }}
  AWS_BUCKET_NAME: stol-apt-repository

jobs:
  build-package:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/usdot-fhwa-stol/carma-builds:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt update
          ./install_dependencies.sh
      - name: Build
        run: |
          ./build.sh -c
      - name: Setup deb-s3
        uses: usdot-fhwa-stol/actions/setup-deb-s3@main
      - name: Upload .deb files
        run: |
          deb-s3 upload --codename develop --bucket ${{ env.AWS_BUCKET_NAME }} build/_packages/*.deb
      - name: Coverage
        run: |
          apt-get install -y jq python3-pip
          pip3 install gcovr
          /opt/carma/scripts/coverage.sh
