name: CI

on:
  pull_request:
  push:

jobs:
  build-package:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/usdot-fhwa-stol/carma-builds:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt update
          ./install_package.sh
      - name: Build
        run: |
          ./build.sh
