on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
#    branches:
#      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Sonar Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/usdot-fhwa-stol/carma-builds:latest
    steps:
    - name: Run sonar scan
      uses: usdot-fhwa-stol/actions/sonar-scanner-cpp@sonar-scanner-cpp
