on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
#    branches:
#      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Sonar Workflow
jobs:
  sonarcloud:
    uses: usdot-fhwa-stol/actions/workflows/sonar-scanner-cpp@sonar-scanner-cpp
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      sonarcloud-token: ${{ secrets.SONAR_TOKEN }}
